DATABASE="avinya_db2"
HOST="localhost"
PASSWORD="Admin@#123"
PORT=3306
USER="root"
GOOGLEDRIVECLIENTID="41484435829-0708j8vve4iemqmpeg66sdjh5ieuii1b.apps.googleusercontent.com"
GOOGLEDRIVECLIENTSECRET="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"
GOOGLEDRIVEREFRESHTOKEN="1//0gLWjkBtRaOHpCgYIARAAGBASNwF-L9IraGYflRXeB46KvyHLLxvaGczzLZUUXUMs-bY8dySkmGcjlZif8Qca6xUH1kd6XeqoNJg"
GOOGLEDRIVEREFRESHURL= "https://oauth2.googleapis.com/token"
GOOGLEDRIVEJOBSCVSCLIENTID="41484435829-0708j8vve4iemqmpeg66sdjh5ieuii1b.apps.googleusercontent.com"
GOOGLEDRIVEJOBSCVSCLIENTSECRET="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"
GOOGLEDRIVEJOBSCVSREFRESHTOKEN= "1//0gLWjkBtRaOHpCgYIARAAGBASNwF-L9IraGYflRXeB46KvyHLLxvaGczzLZUUXUMs-bY8dySkmGcjlZif8Qca6xUH1kd6XeqoNJg"
GOOGLEDRIVEJOBSCVSREFRESHURL="https://oauth2.googleapis.com/token"
ALUMNI_CV_REQUEST_EMAIL = "lahiru@avinya.edu.lk"
ALUMNI_CV_REQUEST_SENDER_EMAIL = "lahiru@avinya.edu.lk"
ALUMNI_CV_REQUEST_SENDER_EMAIL_APP_PASSWORD = ""
FCM_URL = ""
FCM_SERVER_KEY = ""
FCM_SCOPE = ""
FCM_CLIENT_EMAIL = ""
FCM_TOKEN_URL = ""
FCM_PROJECT_ID = ""
